# Global settings applied to the whole site.
[build]
  command = "gulp build"
  publish = "dist/"

[context.miwa-project]
  command = "gulp build && mv ._headers dist/_headers"

[context.dayly-branch]
  command = "gulp build && mv ._headers dist/_headers"

[context.develop]
  command = "gulp build && mv ._headers dist/_headers"

[context.master]
  command = "gulp build && mv ._headers dist/_headers"
