version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - run: yarn install
      - run: yarn run test:ci
      - store_test_results:
        path: reports
      - store_artifacts:
        path: coverage