import '~/stylus/style'
import '~/js/utils/device'
import '~/js/modules/picturefill'
import '~/js/modules/alert'
import '~/js/modules/what-input'
import '~/js/modules/barba'
import '~/js/modules/luxy'
